import { useCallback, useEffect, useState } from "react";
import { Badge } from "./Badge.js";
import { Button } from "./Button.js";
import { Card } from "./Card.js";
import { RequirementAccordion } from "./RequirementAccordion.js";
import { EmptyState, ErrorState, LoadingState } from "./StateViews.js";
import { IconClock, IconSparkles } from "./icons.js";
import { ApiError } from "../services/apiClient.js";
import {
  activateRequirementsVersionRequest,
  analyzeRequirementsRequest,
  listRequirementsVersionsRequest,
  updateRequirementsVersionRequest,
} from "../services/requirementsApi.js";
import type { RequirementsContent, RequirementsVersion } from "../types/requirements.js";

type ListState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "ready"; versions: RequirementsVersion[] };

const EXAMPLE_IDEAS = [
  "A collaborative code review tool that highlights security vulnerabilities and suggests fixes automatically.",
  "A SaaS dashboard that lets small teams track on-call incidents and generates a postmortem draft.",
  "A CLI that scaffolds a REST API from a plain-English description of its resources.",
];

const MIN_IDEA_LENGTH = 10;
const MAX_IDEA_LENGTH = 2000;

function linesToList(text: string): string[] {
  return text
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

function listToLines(items: string[]): string {
  return items.join("\n");
}

function IdeaForm({
  onSubmit,
  submitting,
  error,
  submitLabel,
}: {
  onSubmit: (idea: string) => void;
  submitting: boolean;
  error: string | null;
  submitLabel: string;
}) {
  const [idea, setIdea] = useState("");

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center justify-between">
        <label htmlFor="requirements-idea" className="text-sm font-medium text-text">
          Project idea
        </label>
        <span className="font-mono text-[11px] text-text-faint">
          {idea.length}/{MAX_IDEA_LENGTH}
        </span>
      </div>
      <textarea
        id="requirements-idea"
        rows={7}
        value={idea}
        maxLength={MAX_IDEA_LENGTH}
        onChange={(e) => setIdea(e.target.value)}
        placeholder="Describe the idea in a few sentences — what it does, who it's for..."
        className="rounded-lg border border-border bg-surface-2 px-3.5 py-3 text-sm leading-relaxed text-text placeholder:text-text-faint transition-colors focus-visible:border-accent focus-visible:bg-surface focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/25"
      />
      <div className="flex flex-col gap-1.5">
        <p className="text-[11px] font-medium uppercase tracking-wide text-text-faint">Example prompts</p>
        <div className="flex flex-col gap-1.5">
          {EXAMPLE_IDEAS.map((example) => (
            <button
              key={example}
              type="button"
              onClick={() => setIdea(example)}
              className="rounded-lg border border-border bg-surface px-3 py-2 text-left text-xs text-text-muted transition-colors hover:border-accent hover:bg-accent-soft hover:text-text"
            >
              {example}
            </button>
          ))}
        </div>
      </div>
      {error && (
        <p className="rounded-lg border border-danger/30 bg-danger-soft px-3 py-2 text-sm text-danger" role="alert">
          {error}
        </p>
      )}
      <div className="flex items-center gap-3">
        <Button
          type="button"
          loading={submitting}
          disabled={idea.trim().length < MIN_IDEA_LENGTH}
          onClick={() => onSubmit(idea.trim())}
        >
          <IconSparkles className="h-4 w-4" />
          {submitLabel}
        </Button>
        <span className="text-xs text-text-faint">Generated by your configured AI provider</span>
      </div>
    </div>
  );
}

/**
 * Rendered with `key={version.id}` by the parent, so switching which
 * version is selected remounts this component with fresh state — the
 * idiomatic React way to reset local state from a prop change, instead of
 * an effect + setState (which eslint-plugin-react-hooks flags as a
 * cascading-render risk; see the matching comment in Projects.tsx from the
 * Foundation phase).
 */
function VersionDocument({
  projectId,
  version,
  onActivated,
  onSaved,
}: {
  projectId: string;
  version: RequirementsVersion;
  onActivated: (version: RequirementsVersion) => void;
  onSaved: (version: RequirementsVersion) => void;
}) {
  const [draft, setDraft] = useState<RequirementsContent>(version.content);
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [activating, setActivating] = useState(false);

  async function handleActivate() {
    setActivating(true);
    try {
      const { version: activated } = await activateRequirementsVersionRequest(projectId, version.id);
      onActivated(activated);
    } catch {
      // The version list is unaffected by a failed activation; the button
      // simply re-enables, which is sufficient feedback here.
    } finally {
      setActivating(false);
    }
  }

  async function handleSave() {
    setSaving(true);
    setSaveError(null);
    try {
      const { version: saved } = await updateRequirementsVersionRequest(projectId, version.id, draft);
      onSaved(saved);
    } catch (err) {
      setSaveError(
        err instanceof ApiError ? err.message : "Couldn't save your changes. Please try again.",
      );
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="flex flex-col gap-8">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-5">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-semibold text-text">
            Version {version.version}
            {version.isActive && " (active)"}
          </h2>
        </div>
        {!version.isActive && (
          <Button type="button" variant="secondary" size="sm" loading={activating} onClick={handleActivate}>
            Make active
          </Button>
        )}
      </div>

      <section className="flex flex-col gap-1.5">
        <h3 className="text-xs font-semibold uppercase tracking-wide text-text-faint">Summary</h3>
        <label htmlFor="req-summary" className="sr-only">
          Project summary
        </label>
        <textarea
          id="req-summary"
          rows={3}
          value={draft.projectSummary}
          onChange={(e) => setDraft({ ...draft, projectSummary: e.target.value })}
          className="rounded-lg border border-border bg-surface-2 px-3.5 py-2.5 text-[15px] leading-relaxed text-text focus-visible:border-accent focus-visible:outline-none"
        />
      </section>

      <section className="grid grid-cols-1 gap-5 sm:grid-cols-2">
        {(
          [
            ["users", "User roles"],
            ["features", "Features"],
            ["risks", "Risks"],
            ["constraints", "Constraints"],
            ["assumptions", "Assumptions"],
            ["openQuestions", "Open questions"],
          ] as const
        ).map(([field, label]) => (
          <div key={field} className="flex flex-col gap-1.5">
            <h3 className="text-xs font-semibold uppercase tracking-wide text-text-faint">{label}</h3>
            <label htmlFor={`req-${field}`} className="sr-only">
              {label}
            </label>
            <textarea
              id={`req-${field}`}
              rows={3}
              value={listToLines(draft[field])}
              onChange={(e) => setDraft({ ...draft, [field]: linesToList(e.target.value) })}
              placeholder="One per line"
              className="rounded-lg border border-border bg-surface-2 px-3.5 py-2.5 text-sm text-text placeholder:text-text-faint focus-visible:border-accent focus-visible:outline-none"
            />
          </div>
        ))}
      </section>

      <section>
        <h3 className="text-xs font-semibold uppercase tracking-wide text-text-faint">
          Functional requirements <span className="text-text-faint">({draft.functionalRequirements.length})</span>
        </h3>
        <div className="mt-2.5 flex flex-col gap-2">
          {draft.functionalRequirements.map((item, i) => (
            <RequirementAccordion key={item.id} item={item} index={i} />
          ))}
        </div>
      </section>

      {draft.nonFunctionalRequirements.length > 0 && (
        <section>
          <h3 className="text-xs font-semibold uppercase tracking-wide text-text-faint">
            Non-functional requirements{" "}
            <span className="text-text-faint">({draft.nonFunctionalRequirements.length})</span>
          </h3>
          <div className="mt-2.5 flex flex-col gap-2">
            {draft.nonFunctionalRequirements.map((item, i) => (
              <RequirementAccordion key={item.id} item={item} index={i} />
            ))}
          </div>
        </section>
      )}

      <div className="flex items-center gap-3 border-t border-border pt-5">
        {saveError && (
          <p className="rounded-lg border border-danger/30 bg-danger-soft px-3 py-2 text-sm text-danger" role="alert">
            {saveError}
          </p>
        )}
        <Button type="button" loading={saving} onClick={handleSave}>
          Save changes
        </Button>
      </div>
    </div>
  );
}

export function RequirementsSection({ projectId }: { projectId: string }) {
  const [state, setState] = useState<ListState>({ status: "loading" });
  const [selectedVersionId, setSelectedVersionId] = useState<string | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [analyzeError, setAnalyzeError] = useState<string | null>(null);

  const fetchVersions = useCallback(() => {
    listRequirementsVersionsRequest(projectId)
      .then(({ versions }) => {
        setState({ status: "ready", versions });
        setSelectedVersionId((current) => {
          if (current && versions.some((v) => v.id === current)) return current;
          return versions.find((v) => v.isActive)?.id ?? versions[0]?.id ?? null;
        });
      })
      .catch(() => setState({ status: "error", message: "Couldn't load requirements." }));
  }, [projectId]);

  useEffect(() => {
    fetchVersions();
  }, [fetchVersions]);

  const retryList = useCallback(() => {
    setState({ status: "loading" });
    fetchVersions();
  }, [fetchVersions]);

  const selectedVersion =
    state.status === "ready" ? state.versions.find((v) => v.id === selectedVersionId) : undefined;

  async function handleAnalyze(idea: string) {
    setAnalyzing(true);
    setAnalyzeError(null);
    try {
      const { version } = await analyzeRequirementsRequest(projectId, idea);
      setState((prev) =>
        prev.status === "ready"
          ? { status: "ready", versions: [version, ...prev.versions.map((v) => ({ ...v, isActive: false }))] }
          : { status: "ready", versions: [version] },
      );
      setSelectedVersionId(version.id);
    } catch (err) {
      setAnalyzeError(
        err instanceof ApiError ? err.message : "Something went wrong. Please try again.",
      );
    } finally {
      setAnalyzing(false);
    }
  }

  function replaceVersion(updated: RequirementsVersion, deactivateOthers: boolean) {
    setState((prev) =>
      prev.status === "ready"
        ? {
            status: "ready",
            versions: prev.versions.map((v) =>
              v.id === updated.id ? updated : deactivateOthers ? { ...v, isActive: false } : v,
            ),
          }
        : prev,
    );
  }

  if (state.status === "loading") {
    return <LoadingState label="Loading requirements…" />;
  }

  if (state.status === "error") {
    return <ErrorState message={state.message} onRetry={retryList} />;
  }

  if (state.versions.length === 0) {
    return (
      <Card>
        {analyzing ? (
          <LoadingState label="Analyzing your idea — this can take up to a minute…" />
        ) : (
          <EmptyState
            icon={<IconSparkles className="h-5 w-5" />}
            title="No requirements yet"
            description="Describe the project idea and DevForge will analyze it into structured, versioned requirements."
            action={
              <div className="mx-auto w-full max-w-md text-left">
                <IdeaForm
                  onSubmit={handleAnalyze}
                  submitting={analyzing}
                  error={analyzeError}
                  submitLabel="Analyze"
                />
              </div>
            }
          />
        )}
      </Card>
    );
  }

  return (
    <div className="flex flex-col gap-6 lg:flex-row lg:items-start">
      <div className="flex w-full shrink-0 flex-col gap-5 lg:w-[22rem]">
        <Card>
          <h3 className="text-sm font-semibold text-text">New analysis</h3>
          <p className="mt-1 text-xs text-text-muted">Creates a new version and makes it active. Existing versions are kept.</p>
          <div className="mt-3">
            <IdeaForm onSubmit={handleAnalyze} submitting={analyzing} error={analyzeError} submitLabel="Analyze" />
          </div>
        </Card>

        <Card>
          <h3 className="text-sm font-medium text-text">Versions</h3>
          <ul className="mt-2.5 flex flex-col gap-1">
            {state.versions.map((v) => (
              <li key={v.id}>
                <button
                  type="button"
                  onClick={() => setSelectedVersionId(v.id)}
                  className={`flex w-full items-center justify-between gap-2 rounded-lg px-2.5 py-2 text-left text-sm transition-colors ${
                    v.id === selectedVersionId
                      ? "bg-accent-soft text-accent"
                      : "text-text-muted hover:bg-surface-2 hover:text-text"
                  }`}
                >
                  <span className="flex items-center gap-2">
                    <span>v{v.version}</span>
                    {v.isActive && <Badge tone="accent">active</Badge>}
                  </span>
                  <span className="flex items-center gap-1 text-[11px] text-text-faint">
                    <IconClock className="h-3 w-3" />
                    {new Date(v.createdAt).toLocaleDateString()}
                  </span>
                </button>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <div className="min-w-0 flex-1">
        {selectedVersion && (
          <Card>
            <VersionDocument
              key={selectedVersion.id}
              projectId={projectId}
              version={selectedVersion}
              onActivated={(updated) => replaceVersion(updated, true)}
              onSaved={(updated) => replaceVersion(updated, false)}
            />
          </Card>
        )}
      </div>
    </div>
  );
}
